project:
  type: website
  render:
    - "*.qmd"
    - "!manuscript/"
    - "!README.qmd"
  resources:
    - manuscript/_book/
    - manuscript/main.pdf

  preview: 
    port: 3333
    watch-inputs: true
    navigate: true

website:
  title: "The African Debt Database Project: Exploring Macroeconomic Volatility and Financial Frictions in Sub-Saharan Africa"
  favicon: static/favicon.svg
  navbar:      
    right:
      - icon: globe
        href: https://fukuihirotaka.github.io/
      - icon: envelop
        href: mailto:227e127e@gsuite.kobe-u.ac.jp
      - icon: {{< ai orcid >}} 
        href: https://orcid.org/0009-0004-9796-9148
      - icon: github
        href: https://github.com/FukuiHirotaka/diligent-deer
format:
  html:
    theme:
      - journal
      - static/custom.scss

execute: 
  freeze: auto

knitr:
  opts_chunk: 
    fig.align: center
    fig.retina: 3
    fig.width: 6
    fig.height: 3.708
    dev: svg
